### ISSUE TITLE
Should this repo be private?

### ISSUE THREAD

**Issue by crichID** [certify/curriculum-github#137]
I know we talked about this at one time, but it is still public. @PeterBell what are your thoughts on this?

**Comment by timlombardo** [comment]
I think it's best that we make it private since we're beginning to put feedback from customers and details regarding the platform in the issues (thank you for adding those @crichID!). This will prevent any references to particular customers or users for purposes of diagnosing issues from being public.

**Comment by PeterBell** [comment]
Hey @johnpaulashenfelter what do we need to do to make this happen? Want to create a private repo on wheelhouse org and kill this?

**Comment by crichID** [comment]
hey @PeterBell and @johnpaulashenfelter what is the status on making this a private repo??

**Comment by PeterBell** [comment]
Hi @crichID sorry - just back from offsite - I'll get with JP on this first thing tomorrow morning and we'll figure it out!

**Comment by crichID** [comment]
@PeterBell just a friendly ping on this ^^

**Comment by PeterBell** [comment]
Thanks @crichID - sorry - will get with @johnpaulashenfelter - my bad :(

**Comment by johnpaulashenfelter** [comment]
@crichID A private repo works fine, but there are a _ton_ of complexity in the user flow. The most common problem would be not having a paid account (thus no private repos). For small accounts we'd be taking a slot they're paying for. And if we just offer the option to make the repo private, we generate support traffic for folks that want it but can't have it because of limits, permissions, or organization access.

We're assuming GitHub newbies are using the app which means we should be careful about adding the complexity of account setup (paid plans) and permission management at step one.

There's absolutely no reason a user can't toggle it to private if they wish. I'd rather they make the decision. It could even be part of a GitHub-focused module...

**Comment by crichID** [comment]
@johnpaulashenfelter to clarify I am referring to the actual curriculum repo, not the template repo we create for the students.

**Comment by 1point618** [comment]
As long as import works for private repos, I agree that we can make this private no problem.

The big question is that I know that GitHub has promised to keep all of their education _content_ open source. How do we plan on continuing to do that if this particular repo is private, @crichID?

**Comment by johnpaulashenfelter** [comment]
@crichID @1point618 Repo importer uses the current user's GItHub token so private shouldn't be an issue.

**Comment by crichID** [comment]
@1point618 the open source curriculum is separate and displayed on GitHub's training page. I do not want to maintain several different open source curricula. Since this must be it's own repo than I would prefer to direct open source contributions to the training-kit.

**Comment by PeterBell** [comment]
Cool, so just to be clear, is everyone OK with me making this private? I can do that today if OK @crichID and @1point618

**Comment by 1point618** [comment]
:+1:

**Comment by crichID** [comment]
:+1:

**Comment by PeterBell** [comment]
It's now private - @crichID @1point618 and @johnpaulashenfelter just ping me if you run into any issues!

**Comment by PeterBell** [comment]
Oops - just testing the free course. It uses images straight from this repo which didn't show up because the repo was private. I've made the repo public for now again and reopened issue. @crichID I'll get with @johnpaulashenfelter before our call on the 4th to figure out what we need to do to make the repo private and how big a deal it's going to be. Then we can all discuss it that afternoon. cc @1point618

**Comment by johnpaulashenfelter** [comment]
@PeterBell images will have to be moved as part of the import if we go down this path -- didn't think about that since its "always worked for me" because I've got access to the repo.

Since we're on Heroku this means integrating with Amazon S3 or similar.
