### ISSUE TITLE
Request for Video Transcripts

### ISSUE THREAD

**Issue by crichID** [certify/curriculum-github#178]
A customer has requested a transcript of the videos:

> It would be great for people who are hard of hearing if the videos could
> either be fully transcribed or actual (not automatic) closed captions added
> to the video.
> The video by itself does not provide enough information for users, and even
> though there is a recap, the video has extra information that is useful for
> users.
> The automated closed caption is not at all reliable or able to be
> understood.
> 
> The transcription could be accessed though a link on the same page as the
> video, which would be easier than actually setting up closed caption on the
> video and would provide the same service.

FWIW, if we do the transcripts on the video pages, it would also partially solve the #177 China :-1: YouTube issue.

This would require some engineering effort to add the transcript to the page, but the transcripts are pretty much all in the YAML files.

**Comment by PeterBell** [comment]
Gong to cc @johnpaulashenfelter and @1point618 I'm certainly open to sharing the copy, but I think we'd just have to think through carefully how it would look. I do agree that we need a solution for the deaf, so having at least the text for the videos available would be useful. Any thoughts on how we might want something like this to work anyone?

**Comment by crichID** [comment]
@PeterBell a fairly low tech solution would be to add a link to a PDF (but a pain to keep up to date).

The better option would be to use a collapsable panel that would pull the text from the YML files like the instructor script did.

**Comment by PeterBell** [comment]
Agreed on both accounts @crichID - let's see what @1point618 and @johnpaulashenfelter have to say . . .

**Comment by johnpaulashenfelter** [comment]
At Treehouse, we used https://cielo24.com/ to transcribe finished videos -- we automated it as part of the production process. Transcriptions were relatively inexpensive as I remember it. I'm sure there are a ton of other options.

I will say "git" particularly was an issue -- also funny technical mis-transcriptions. But it was pretty straightforward. As I recall it took about 48h. We'd usually post the script (which was about 75% accurate by the time the video was shot) and then replace with the transcript. A _lot_ of people used the transcript. And as far as the deaf go, the Cielo24 transcripts would be time-indexed (and could be turned on as captions as well -- [music] and [laugher] for example).

If there's a real script that's accurate, that works just fine without post-production transcription -- just post the PDF. Keep in mind the video at Treehouse was shot more like a commercial news segment than the more traditional training video like these so post-production led to many more changes from the original script (not to mention ~4-10x shooting-to-finished time ratio).

That said, at General Assembly folks asked for transcripts and we said "one day". The few that we did have accurate scripts for, we sold as an add-on :)

Its easy enough to try converting a few -- I'm not 100% sure how you add third-party captioning/etc to _youtube_ videos. At Treehouse we had our own infrastructure.

As I think about it -- Wistia also does transcription and cancelling as an add-on service but they don't really advertise it. Or maybe the stopped :shrug

**Comment by 1point618** [comment]
I think video transcripts are a good idea generally.

My personal feelings are that we want two different things here: 
1. Captioning on the videos. The videos were carefully designed to allow a person to follow along and get relevant information about what's happening on screen while it happens. Neither the video nor the audio/transcript are sufficient for learning.
   
   Useful for: people who are deaf, people who speak English as a second level at an intermediate level. 
2. Text transcript of the video w/ relevant images or gifs. As per above, the text along isn't enough to teach people because it was designed to be paired with specific visual elements. Due to this, I don't think that just publishing the transcript is really an answer to our user's issues. We need to find a way to keep that visual element. 
   
   Useful for: people who cannot access youtube, people who speak English as a second language at a beginner level. 

Either of these will require that we first have an accurate transcript, so I think in the short term we should absolutely begin transcribing the videos. I agree with @johnpaulashenfelter that we should just get a service to do this, then do one final pass-through for the technical jargon ourselves rather than trying to line up the scripts or make our own transcripts. Being time-indexed means that we can pretty much just upload these to youtube and get (1) for free, and can also begin thinking about (2) in parallel.
