### ISSUE TITLE
Discussion of feedback on the platform

### ISSUE THREAD

**Issue by PeterBell** [certify/curriculum-github#50]
This is the first real course, so @crichID as you get feedback from anyone on improvements we could make to the platform, please ask them to add it to the conversation here.

**Comment by crichID** [comment]
@PeterBell this seemed like a better solution than email for this conversation so all could see. If there are questions, we can more easily discuss below:
- [ ] We need a way to separate screen navigation instructions from general text that appears in polls. For example, on the bottom of the first poll page, there is a message that says "Thanks for your response. You may continue to the next screen." This doesn't make sense during a facilitator led course. 
- [ ] The presenter script is still not appearing at the top of the lab screen.
- [ ] We need a link to the class repo when users are being asked to go there to complete a lab.
- [ ] We need a way to archive old events from the Admin screen. We would like a way to filter the Archived events by date, customer, and class type (which version of the curriculum did they use?) 
- [ ] We would like a way to decide whether or not to share poll results with the class.
- [ ] We need the ability to easily jump between sections and topics. We talked about the drop down list before but it is still not included.
- [ ] In the say sections of the do/say blocks, we would like the ability to do bullets.
- [ ] since the trainer doesn’t need the video/image, could we put the instructor notes there and put a thumbnail of the image or video in the notes section. This would allow us to bump up the font a little on the script as well!
- [ ] While in a facilitated session, we want the option to completely turn off the videos. Instead of showing the video we would like to show them a generic message like “watch the instructor screen demo”
- [ ] We would like to be able to jump to slides by slide number
- [ ] It would also be nice to have a visual library of all the slides (like a carousel where we could jump to a specific slide)
- [ ] On the video screens - the pre-view shows up as the top 1/3 of the video container. When you click play it expands to full size.
- [ ] When we typed an answer in the first box for the Exploring a Repository quiz and pressed enter on the student screen we were popped back to the version control poll on page one.
-  [ ] When we answered only the first question, all responses were graded (not just the ones we answered). The incorrect feedback was shown in green. It seems incorrect should be shown in red and correct should appear in green.
- [ ] The team has requested that the curriculum repo be put under a direct org account instead of a user account. 
- [ ] On unverified labs, we would like an “i’m done” button. This should report towards the % complete for the page.
- [ ] They really want the "What's up next " at the bottom of the slide.
- [ ] We would like to add an estimated time for labs along with an on-screen timer. The facilitator will give the instruction to start and then press a start button. They should have an additional button to stop the timer if everyone has finished early.
- [ ] We would like an integrated timer for break time
- [ ] Can we automate a contact slide for the end of the course based on who is the instructor

**Comment by matthewmccullough** [comment]
CC @PatrickBM @jaw6 @brntbeer @loranallensmith @jordanmccullough

**Comment by PeterBell** [comment]
This is pretty old, so closing for now.
